### ISSUE TITLE
Integration JS-OptOut

### ISSUE THREAD

**Issue by frontendschlampe** [menatwork/contao-MatomoTrackingTag-Bundle#1]
wie besprochen würden wir ein JS-OptOut mit einbauen. Benötigt dazu wird: https://plugins.matomo.org/AjaxOptOut

Wir machen die Änderungen bei uns im Fork https://github.com/hofff/contao-MatomoTrackingTag-Bundle und stellen dann einen PR

**Comment by frontendschlampe** [comment]
- Inhaltselement Matomo OptOut
- noscript Fallback mit iFrame
- Hinweis, wenn Matomo Plugin nicht installiert (direkt im Backend, blaues Hinweisfenster)
- es wird folgende Buttons und Texte geben:
  - wenn Tracking aktiv, gibt es einen Button zum deaktivieren
  - wenn Tracking deaktiviert, gibt es einen Button zum aktivieren
  - Hinweismeldung (TinyMCE), ob Tracking aktiviert oder deaktiviert
  - **Buttonbeschriftung und Texte muss jeder Websitebetreiber selbst pflegen**

**Comment by davidmaack** [comment]
Closed, da schon längst gemerged
