### ISSUE TITLE
Invalid Schema

### ISSUE THREAD

**Issue by dhaeb** [menatwork/contao-MatomoTrackingTag-Bundle#10]
Hallo liebes MatomoTrackingTag Bundle Team,

ich habe mit Contao 4.4.44 und Matomo 3.12.0 folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/3354824/68207879-3d67bd00-ffd0-11e9-8710-e363dfeda17c.png)
Dabei ist es besonders ärgerlich - da das Plugin in der Vergangenheit bereits installiert war. Es schaut ein wenig wie ein DB Fehler aus - aber das Contao Installtool zeigt keine Fehler an. 

Könnt Ihr mir bitte erläutern, wo ich weitere Informaitonen zum Fehler / Logs finde?
Woran könnte es liegen?

Beste Grüße

Dan

**Comment by davidmaack** [comment]
Hallo Dan,,

ist das noch aktuell? Bei uns ins der Fehler nie aufgetreten. 

BG,
David

**Comment by dhaeb** [comment]
Hey David, 
leider nutzen wir das ganze schon gar nicht mehr. Haben auch nun neueres Contao.
Ich schließe daher mal das Issue.
Beste Grüße
