### ISSUE TITLE
'Entry "Include Matomo javascript tag into the site" is missing from Website Root (Contao 4.9.5)

### ISSUE THREAD

**Issue by joehi** [menatwork/contao-MatomoTrackingTag-Bundle#11]
In Contao 4.9 the entry "Include Matomo javascript tag into the site" is missing in the Website Root if at the DNS setting the checkbox "Language fallback" is selected. For the non fallback languages the entry "Include Matomo javascript tag into the site" is accessible.
It seems there were some changes with the introduction of Contao version 4.9 according to a discussion in the [German Contao forum](https://community.contao.org/de/showthread.php?78677-Contao-Bug-Sprachen-Fallback-ver%C3%A4ndert-DCA&p=530137&viewfull=1#post530137).

**Comment by Total-Reality** [comment]
Can you fix it please?
This is a bug which exists in Contao 4.9+ only.

I added the following code in line 17 of the file vendor\menatwork\contao-matomotrackingtag-bundle\src\Resources\contao\dca\tl_page.php

`$GLOBALS['TL_DCA']['tl_page']['palettes']['rootfallback'] = str_replace('{publish_legend', '{piwik_legend},piwikEnabled;{publish_legend', $GLOBALS['TL_DCA']['tl_page']['palettes']['rootfallback']);
`

**Comment by stefanheimes** [comment]
We will add a check if the rootfallback is set and add all the fields to this palette as well.

**Comment by stefanheimes** [comment]
Fixed in the new version 1.2.1 @Total-Reality  @joehi

**Comment by joehi** [comment]
Thank you for the fix.
