### ISSUE TITLE
Matomo Plugin not ready for PHP 8.x/ 8.1.x

### ISSUE THREAD

**Issue by mr2017x** [menatwork/contao-MatomoTrackingTag-Bundle#13]
Hi Guys,

is there a reason that the plugin is not ready for php 8.(1)

Thanks

**Comment by stefanheimes** [comment]
Nope not really, I will add php8 to the composer.json. If you found any problem let me know.

**Comment by stefanheimes** [comment]
Fixed, please test @mr2017x

**Comment by mr2017x** [comment]
great, i will test after some other plugins also did that move
