### ISSUE TITLE
PiwikTrackingTag.php references the wrong templates

### ISSUE THREAD

**Issue by HaraldHubinger** [menatwork/contao-MatomoTrackingTag-Bundle#6]
PiwikTrackingTag.php seems to reference old template names ("mod_piwik[...]html5", should be "mod_matomo[...]html5") which the template loader does not find on lines 21, 103 and 347.

I will make a pull request with my proposal for correction.

**Comment by HaraldHubinger** [comment]
Thanks for merge and release as 1.1.1.
Packagist still shows 1.1.0 as the latest version which breaks my install as long as I don't reference my own "fork" in my project's composer.json. If that's not intended, please also push the release to packagist.

**Comment by davidmaack** [comment]
packagist shows version 1.1.1
