### ISSUE TITLE
Modifiziertes Template im template Ordner wird nicht gefunden

### ISSUE THREAD

**Issue by chriza** [menatwork/contao-MatomoTrackingTag-Bundle#9]
Frische Contao 4.8.4 Installation
contao-matomotrackingtag-bundle Version 1.1.1

1. Verbindung zu einer Matomo-Installation herstellen mit asynchronem Template
2. Neues Template erstellen : mod_matomo_TrackingTagAsynchron
3. Fehlermeldung im FE: Could not find template "mod_matomo_TrackingTagAsynchron (global)"

**Comment by davidmaack** [comment]
Fixed in 1.2.0
